version: '3.8'

services:
  unidash-api:
    build: .
    container_name: unidash-api
    restart: always
    ports:
      - '3333:3333'
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - unidash-api
      - certbot

  postgres:
    image: postgres:16
    container_name: unidash-pg
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${EXTERNAL_DB_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"
volumes:
  postgres_data:
