services:
  unidash-api:
    container_name: unidash-api
    image: unidash-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - '3333:3333'
      - '5555:5555'
    depends_on:
      - postgres
    networks:
      - backend-unidash

  postgres:
    container_name: unidash-pg
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: unidash
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - backend-unidash

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@unidash.com
      PGADMIN_DEFAULT_PASSWORD: unidash
    ports:
      - 5050:80
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./pgadmin:/var/lib/pgadmin/storage/admin_unidash.com

  mailhog:
    image: mailhog/mailhog
    container_name: unidash-mailhog
    restart: 'no'
    ports:
      - 1025:1025 # SMTP
      - 8025:8025 # Web UI

networks:
  backend-unidash:
    name: unidash-network
    external: true

volumes:
  postgres:
  pgadmin:
